title: "Andrew Carr Portfolio"
description: "A portfolio of my engineering projects"
url: "https://andrewpatcarr.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

navigation:
  - title: "Main"
    url: /
    children:
      - title: "Projects"
        url: /projects/
      - title: "About"
        url: /about/
      - title: "Contact"
        url: /contact/

minimal_mistakes_skin: "neon"