title: "Andrew Carr"
description: "A portfolio of my engineering projects"
url: "https://andrewpatcarr.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

minimal_mistakes_skin: "contrast" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise

collections:
  projects:
    output: true
    permalink: /projects/:path/

include:
  - /assets/css/custom.css

defaults:
  - scope:
      path: ""
      type: projects
    values:
      entries_layout: grid
      classes: wide

navigation:
  - title: "Main"
    url: /
    children:
      - title: "Projects"
        url: /projects/
      - title: "About"
        url: /about/
      - title: "Contact"
        url: /contact/

