title: "Andrew Carr Portfolio"
description: "A portfolio of my engineering projects"
url: "https://andrewpatcarr.github.io"  # Change this to your GitHub Pages URL
baseurl: ""  # Leave empty if you're using your user/organization GitHub Pages site

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

navigation:
  - title: "Main"
    url: /
    children:
      - title: "Projects"
        url: /projects/
      - title: "About"
        url: /about/
      - title: "Contact"
        url: /contact/

minimal_mistakes_skin: "air"  # Try "default", "air", "dark", "mint", etc.